### ISSUE TITLE
netbox2aquilon crashes if a device does not have a role set

### ISSUE THREAD

**Issue by jrha** [stfc/Netbox-utils#5]
e.g.
```
Traceback (most recent call last):
  File "/var/quattor/bin/netbox2aquilon", line 379, in <module>
    _netbox_copy(OPTS)
  File "/var/quattor/bin/netbox2aquilon", line 291, in _netbox_copy
    personality = f'{device.role.slug}-{device.tenant.slug}'
AttributeError: 'NoneType' object has no attribute 'slug'
```

This should probably just fall back to the `inventory` personality.

**Comment by drossy** [comment]
Interesting, in netbox physical devices must have a role, but virtual devices don't
